# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Sample agent using the ARDHF toolset.

Demonstrates the full discover -> inspect -> connect flow using the
HuggingFace Agent Finder (ARD) registries.  The agent can search for
agents, inspect their cards, and connect to remote A2A agents.

Usage::

    adk web contributing/samples/ardhf

Or with the challenge server for deterministic results::

    hf-agentfinder challenge serve --port 8090 &
    ARDHF_REGISTRY_URL=http://127.0.0.1:8090 \
        adk web contributing/samples/ardhf
"""

from __future__ import annotations

import asyncio
import os

from google.adk import Agent
from google.adk.runners import InMemoryRunner
from google.adk.tools.tool_context import ToolContext
from google.genai import types

from google.adk_community.tools.ardhf import AgentFinderToolset

# -- Configuration ---------------------------------------------------------

_registry_url = os.environ.get(
    "ARDHF_REGISTRY_URL",
    "https://huggingface.co/api/agentfinder",
)
_local = os.environ.get("ARDHF_LOCAL", "").lower() in (
    "1",
    "true",
    "yes",
)
_token = os.environ.get("HF_TOKEN")


# -- Helper tool -----------------------------------------------------------


async def summarise_findings(
    tool_context: ToolContext,
    findings: str,
) -> str:
  """Format discovery findings into a structured report.

  Args:
    findings: JSON string of search results and inspected cards to
        summarise.

  Returns:
    A formatted markdown report of the findings.
  """
  return (
      "## Discovery Report\n\n"
      f"{findings}\n\n"
      "_Report generated by ARDHF discovery agent._"
  )


# -- Agent -----------------------------------------------------------------

agent_finder_toolset = AgentFinderToolset(
    registry_url=_registry_url,
    token=_token,
    local=_local,
)

root_agent = Agent(
    name="ardhf_discovery_agent",
    description=(
        "An agent that discovers and connects to agentic resources "
        "using the HuggingFace Agent Finder (ARD) registry."
    ),
    instruction=(
        "You are a discovery agent. Your job is to help users find "
        "agents, skills, MCP servers, and other agentic resources by "
        "searching the Agent Finder (ARD) registry, and optionally "
        "connect to and interact with discovered A2A agents.\n\n"
        "## Tools\n\n"
        "You have three discovery tools:\n"
        "1. **search_agents** — search for resources by capability\n"
        "2. **get_agent_card** — inspect a specific resource's card\n"
        "3. **connect_agent** — send a message to a remote A2A agent\n\n"
        "## Workflow\n\n"
        "When a user asks for a capability:\n"
        "1. Use search_agents to find relevant resources.  You can "
        "filter by artifact type: 'skill', 'mcp', 'space', or 'a2a'.\n"
        "2. Summarise the results — name, description, type, and URL.\n"
        "3. If a user wants more details about a specific result, use "
        "get_agent_card with the result's URL.\n"
        "4. If a user wants to interact with a discovered A2A agent, "
        "use connect_agent with the agent card URL and the user's "
        "message.  Only use this for results whose type is "
        "'application/a2a-agent-card+json'.\n\n"
        "Use summarise_findings to create a structured report when "
        "presenting multiple results."
    ),
    tools=[agent_finder_toolset, summarise_findings],
)


# -- Main ------------------------------------------------------------------


async def main() -> None:
  """Run the discovery agent with a sample query."""
  runner = InMemoryRunner(
      agent=root_agent,
      app_name="ardhf_demo",
  )
  session = await runner.session_service.create_session(
      user_id="demo_user",
      app_name="ardhf_demo",
  )

  prompt = "Find A2A agents for code review and connect to the best one"
  print(f"User: {prompt}")

  async for event in runner.run_async(
      user_id="demo_user",
      session_id=session.id,
      new_message=types.Content(
          role="user",
          parts=[types.Part.from_text(text=prompt)],
      ),
  ):
    if event.content and event.content.parts:
      for part in event.content.parts:
        text = getattr(part, "text", None)
        if text:
          print(f"{event.author}: {text}")


if __name__ == "__main__":
  asyncio.run(main())
