# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Sample agent using the ARDHF toolset.

Demonstrates searching HuggingFace's Agent Finder (ARD) registries for
agents, skills, MCP servers, and other agentic resources.

Usage::

    adk web contributing/samples/ardhf

Or with the challenge server for deterministic results::

    hf-agentfinder challenge serve --port 8090 &
    ARDHF_REGISTRY_URL=http://127.0.0.1:8090 \
        adk web contributing/samples/ardhf
"""

from __future__ import annotations

import asyncio
import os

from google.adk import Agent
from google.adk.runners import InMemoryRunner
from google.adk.tools.tool_context import ToolContext
from google.genai import types

from google.adk_community.tools.ardhf import AgentFinderToolset

# -- Configuration ---------------------------------------------------------

_registry_url = os.environ.get(
    "ARDHF_REGISTRY_URL",
    "https://huggingface.co/api/agentfinder",
)
_local = os.environ.get("ARDHF_LOCAL", "").lower() in (
    "1",
    "true",
    "yes",
)
_token = os.environ.get("HF_TOKEN")


# -- Helper tool -----------------------------------------------------------


async def summarise_findings(
    tool_context: ToolContext,
    findings: str,
) -> str:
  """Format discovery findings into a structured report.

  Args:
    findings: JSON string of search results and inspected cards to
        summarise.

  Returns:
    A formatted markdown report of the findings.
  """
  return (
      "## Discovery Report\n\n"
      f"{findings}\n\n"
      "_Report generated by ARDHF discovery agent._"
  )


# -- Agent -----------------------------------------------------------------

agent_finder_toolset = AgentFinderToolset(
    registry_url=_registry_url,
    token=_token,
    local=_local,
)

root_agent = Agent(
    name="ardhf_discovery_agent",
    description=(
        "An agent that searches for agentic resources using the "
        "HuggingFace Agent Finder (ARD) registry."
    ),
    instruction=(
        "You are a discovery agent. Your job is to help users find "
        "agents, skills, MCP servers, and other agentic resources by "
        "searching the Agent Finder (ARD) registry.\n\n"
        "When a user asks for a capability, use the search_agents tool "
        "to find relevant resources. You can filter by artifact type:\n"
        "- 'skill' for AI skills\n"
        "- 'mcp' for MCP servers\n"
        "- 'space' for HuggingFace Spaces\n"
        "- 'a2a' for A2A agent cards\n\n"
        "After finding results, summarise what you found, including the "
        "name, description, type, and URL of each result.\n\n"
        "If a user wants more details about a specific result, use the "
        "get_agent_card tool with the result's URL to fetch its full "
        "descriptor or skill markdown.\n\n"
        "Use summarise_findings to create a structured report."
    ),
    tools=[agent_finder_toolset, summarise_findings],
)


# -- Main ------------------------------------------------------------------


async def main() -> None:
  """Run the discovery agent with a sample query."""
  runner = InMemoryRunner(
      agent=root_agent,
      app_name="ardhf_demo",
  )
  session = await runner.session_service.create_session(
      user_id="demo_user",
      app_name="ardhf_demo",
  )

  prompt = "Find MCP servers for image processing"
  print(f"User: {prompt}")

  async for event in runner.run_async(
      user_id="demo_user",
      session_id=session.id,
      new_message=types.Content(
          role="user",
          parts=[types.Part.from_text(text=prompt)],
      ),
  ):
    if event.content and event.content.parts:
      for part in event.content.parts:
        text = getattr(part, "text", None)
        if text:
          print(f"{event.author}: {text}")


if __name__ == "__main__":
  asyncio.run(main())
